update stagin ci

diff --git a/.github/workflows/staging-api.yml b/.github/workflows/staging-api.yml
--- a/.github/workflows/staging-api.yml
+++ b/.github/workflows/staging-api.yml
@@ -16,7 +16,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Start Docker Compose Services
-        run: docker compose up -d --wait
+        run: docker compose up -d --wait || (echo "One or more services failed their health checks." && docker compose ps && exit 1)
 
       - name: Stop Docker Compose
         if: always()
@@ -29,7 +29,7 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build Docker Image
-        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor-api:staging -f saleor-api/Dockerfile .
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor-api:staging -f saleor-api/Dockerfile
 
       - name: Push Docker Image to DockerHub
         run: docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:staging
